import { prisma } from "../lib/prisma";

export async function articleSeed() {
  const defaultArticles = [
    {
      title: "Flere unge finder fællesskab gennem frivilligt arbejde",
      content:
        "Flere unge vælger i disse år at bruge en del af deres fritid på frivilligt arbejde. For mange handler det ikke kun om at hjælpe andre, men i lige så høj grad om at blive en del af et fællesskab, møde nye mennesker og få erfaringer, som kan bruges både personligt og professionelt. Frivillige organisationer, foreninger og lokale initiativer oplever derfor en stigende interesse fra unge, der gerne vil engagere sig i noget, der giver mening.\n\nEn af de store fordele ved frivilligt arbejde er, at det kan tilpasses den enkeltes hverdag. Nogle unge vælger at hjælpe fast én gang om ugen, mens andre deltager ved enkelte arrangementer eller projekter. Det gør det muligt at være frivillig, selvom man samtidig går i skole, studerer eller har et arbejde.\n\nFor mange unge er det sociale fællesskab en vigtig del af oplevelsen. Når man arbejder sammen om en konkret opgave, opstår der ofte relationer, som kan være svære at skabe i andre sammenhænge. Det kan eksempelvis være gennem en sportsklub, en festival, en ungdomsorganisation eller et lokalt projekt.\n\nFrivilligt arbejde kan også være en måde at prøve forskellige interesser af. En person, der overvejer en uddannelse inden for kommunikation, kan eksempelvis hjælpe med sociale medier eller nyhedsbreve. En anden kan få erfaring med børn gennem en forening, mens en tredje kan prøve kræfter med praktiske opgaver ved events.\n\nSamtidig kan erfaringerne være relevante, når unge senere søger studiejob eller deres første faste arbejde. Frivilligt engagement kan vise, at man tager ansvar, kan samarbejde med andre og er villig til at bidrage til et fælles mål. Det er kompetencer, som mange arbejdsgivere lægger vægt på.\n\nMen måske vigtigst af alt giver frivilligt arbejde mulighed for at gøre en konkret forskel. Uanset om man hjælper børn med sport, arrangerer kulturelle aktiviteter eller bidrager til en lokal forening, kan den enkeltes indsats have betydning for andre mennesker.\n\nFor unge, der overvejer at blive frivillige, er anbefalingen derfor enkel: Start med noget, der interesserer dig. Det behøver ikke være et stort engagement fra begyndelsen. Selv få timer kan være nok til at komme i gang, møde nye mennesker og finde ud af, om frivilligt arbejde er noget, der passer til dig.",
      author: "Sofie Nielsen",
      imageUrl: "/assets/images/article1.jpg",
      createdAt: "2026-03-23T10:56:25.148+00:00",
    },
    {
      title: "Frivillige gør en forskel i lokale foreninger",
      content:
        "Lokale foreninger spiller en vigtig rolle i mange danskeres hverdag. De skaber rammerne for sport, fritidsaktiviteter, kultur og sociale fællesskaber, men bag de mange aktiviteter står ofte en gruppe mennesker, som arbejder frivilligt. Uden deres indsats ville mange foreninger have svært ved at få hverdagen til at fungere.\n\nDe frivillige løser mange forskellige opgaver. Nogle træner børn og unge, mens andre sidder i bestyrelsen, arrangerer turneringer eller hjælper med praktiske opgaver. Der kan også være brug for personer, som kan tage billeder, skrive opslag til sociale medier, administrere en hjemmeside eller hjælpe med økonomi og planlægning.\n\nDet betyder, at frivilligt arbejde i en forening ikke nødvendigvis kræver en bestemt baggrund. Der er plads til mange forskellige kompetencer, og ofte er motivationen vigtigere end tidligere erfaring. En person, der aldrig har arbejdet med events før, kan eksempelvis sagtens lære at hjælpe med et lokalt stævne.\n\nForeningerne oplever samtidig, at det kan være en udfordring at finde nok frivillige. Mange mennesker har travle hverdage med arbejde, familie og andre forpligtelser. Derfor forsøger flere foreninger at gøre det lettere at engagere sig på fleksible vilkår.\n\nDet kan være en fordel for både foreningen og den frivillige. Når opgaverne bliver delt mellem flere personer, behøver ingen nødvendigvis at bruge mange timer hver uge. En person kan måske hjælpe med en enkelt aktivitet, mens en anden tager ansvar for en større opgave.\n\nFor de frivillige kan engagementet give meget tilbage. Det kan være tilfredsstillelsen ved at se børn udvikle sig gennem en sport, glæden ved at skabe et vellykket arrangement eller ganske enkelt følelsen af at høre til i et lokalt fællesskab.\n\nDerudover kan frivilligt arbejde være en god måde at møde mennesker, man ellers ikke ville have mødt. I en forening kan mennesker med forskellige aldre, uddannelser og interesser arbejde sammen om det samme mål.\n\nHvis man overvejer at blive frivillig i en lokal forening, kan det være en god idé at tage direkte kontakt og spørge, hvilke opgaver der er behov for hjælp til. Mange steder er der behov for både små og store bidrag.\n\nEn enkelt frivillig kan måske ikke løse alle foreningens udfordringer, men når mange mennesker bidrager med lidt hver, kan resultatet blive betydeligt. Netop derfor er frivillige fortsat en afgørende del af det lokale foreningsliv.",
      author: "Mikkel Hansen",
      imageUrl: "/assets/images/article2.jpg",
      createdAt: "2026-04-21T11:26:25.148+00:00",
    },
    {
      title: "Sådan kan frivilligt arbejde styrke dit CV",
      content:
        "Når man tænker på erfaring til sit CV, er det ofte tidligere jobs, uddannelser og kurser, der kommer først i tankerne. Men frivilligt arbejde kan også være en værdifuld måde at opbygge erfaring og udvikle kompetencer på. Det gælder især for studerende, unge og jobsøgende, som endnu ikke har mange års erhvervserfaring.\n\nFrivilligt arbejde kan give mulighed for at tage ansvar i situationer, hvor man måske ikke ville få den samme mulighed i sit første job. Man kan eksempelvis få ansvar for sociale medier, koordinering af arrangementer, kommunikation med medlemmer eller planlægning af aktiviteter.\n\nDe erfaringer kan efterfølgende beskrives konkret på CV'et. I stedet for blot at skrive, at man har været frivillig, kan man fortælle, hvilke opgaver man havde ansvar for, og hvilke resultater man var med til at skabe.\n\nDet kan eksempelvis være, at man stod for kommunikationen omkring et arrangement, som samlede flere hundrede deltagere. Det kan også være, at man hjalp med at organisere en aktivitet, oplærte nye frivillige eller udviklede indhold til en organisations sociale medier.\n\nEn anden fordel er, at frivilligt arbejde kan give mulighed for at afprøve en branche eller arbejdsfunktion. Hvis man overvejer en karriere inden for marketing, kan man eksempelvis hjælpe en forening med annoncering og sociale medier. Er man interesseret i IT, kan man arbejde med hjemmeside eller digitale systemer.\n\nDet betyder også, at frivilligt arbejde kan være en måde at opdage, hvad man faktisk interesserer sig for. Nogle gange finder man først ud af, hvilke arbejdsopgaver man trives med, når man prøver dem i praksis.\n\nArbejdsgivere kan desuden se positivt på frivilligt engagement, fordi det ofte viser initiativ og ansvar. Det fortæller noget om, hvordan man samarbejder med andre, håndterer opgaver og bidrager til et fælles mål.\n\nDet er dog vigtigt ikke at se frivilligt arbejde udelukkende som noget, der skal pynte på CV'et. Det fungerer bedst, når man rent faktisk interesserer sig for den organisation eller sag, man arbejder for. Engagementet bliver ofte mere naturligt, og man får samtidig mere ud af erfaringen.\n\nFor personer, der gerne vil styrke deres CV, kan frivilligt arbejde derfor være et oplagt supplement til uddannelse og erhvervserfaring. Det kræver ikke nødvendigvis mange timer, og der findes muligheder inden for næsten alle områder.\n\nDet vigtigste er at finde en opgave, hvor man både kan bidrage og udvikle sig. På den måde bliver frivilligt arbejde ikke bare en linje på CV'et, men en reel erfaring, som kan bruges videre i arbejdslivet.",
      author: "Laura Jensen",
      imageUrl: "/assets/images/article3.jpg",
      createdAt: "2025-07-14T12:23:25.148+00:00",
    },
    {
      title: "Mindre tid? Du kan stadig blive frivillig",
      content:
        "Mange forbinder frivilligt arbejde med faste vagter, ugentlige møder og et stort tidsforbrug. Men sådan behøver det ikke være. I dag findes der mange forskellige former for frivilligt engagement, og flere organisationer tilbyder opgaver, som kan løses fleksibelt og tilpasses den enkeltes hverdag.\n\nDet kan være en fordel for mennesker, der gerne vil gøre en forskel, men som allerede har en travl kalender. Studerende, fuldtidsansatte og børnefamilier kan eksempelvis have svært ved at afsætte flere timer hver uge. Derfor kan mindre opgaver eller enkeltstående arrangementer være en god måde at komme i gang på.\n\nNogle organisationer har brug for frivillige til events, hvor hjælpen kun er nødvendig på bestemte dage. Det kan være en festival, en sportsdag, en indsamling eller et lokalt arrangement. Andre steder kan man hjælpe med konkrete opgaver hjemmefra, eksempelvis med sociale medier, grafisk design eller tekstproduktion.\n\nDet betyder, at frivilligt arbejde i højere grad kan tilpasses den enkelte. Man behøver ikke nødvendigvis binde sig for et helt år for at bidrage. Nogle steder kan man vælge mellem forskellige opgaver og selv bestemme, hvor ofte man ønsker at deltage.\n\nEn fleksibel tilgang kan også gøre det lettere at prøve frivilligt arbejde for første gang. Hvis man er usikker på, hvor meget tid man har, kan man starte med en enkelt opgave og derefter vurdere, om man har lyst til mere.\n\nDer er også en fordel ved at være tydelig omkring sine tidsmæssige muligheder. Organisationerne har brug for at vide, hvad de kan regne med, men de fleste forstår samtidig, at frivillige har andre forpligtelser. En klar aftale fra starten kan derfor gøre samarbejdet lettere for begge parter.\n\nFor nogle bliver den første lille opgave begyndelsen på et længere engagement. Når man først har oplevet fællesskabet og fundet en opgave, man synes er spændende, kan det være naturligt at få lyst til at bidrage mere.\n\nMen det er ikke nødvendigt at gøre frivilligt arbejde til en stor del af sit liv. Selv få timer kan have betydning. En person, der hjælper med at afvikle et arrangement, kan være med til at gøre oplevelsen bedre for mange andre.\n\nHvis du gerne vil være frivillig, men tænker, at du ikke har tid, kan det derfor betale sig at undersøge mulighederne. Der findes sandsynligvis en opgave, der passer bedre til din kalender, end du umiddelbart tror.\n\nFrivilligt arbejde handler i sidste ende ikke om, hvor mange timer man kan give. Det handler om at bruge den tid, man faktisk har, på noget, der skaber værdi for andre.",
      author: "Emil Sørensen",
      imageUrl: "/assets/images/article4.jpg",
      createdAt: "2026-04-11T17:46:25.148+00:00",
    },
    {
      title: "Frivillige skaber liv i byens kulturtilbud",
      content:
        "Når publikum går til koncert, festival eller udstilling, er det ofte de professionelle arrangører og kunstnere, der får opmærksomheden. Men bag mange kulturelle arrangementer står også en stor gruppe frivillige, som sørger for, at praktikken omkring begivenheden fungerer.\n\nFrivillige kan være involveret i mange forskellige dele af et arrangement. Nogle tager imod gæster, andre hjælper ved indgangen eller står for billetsalg. Der kan også være brug for hjælp til opsætning, information, garderobe, servering og oprydning.\n\nFor kulturinstitutioner og arrangører kan frivillige være en vigtig ressource. De kan være med til at skabe en god stemning og give gæsterne en positiv oplevelse. Samtidig får de frivillige mulighed for at komme tæt på det kulturelle miljø og opleve arrangementer fra en anden side.\n\nFor mange er netop fællesskabet en af de største motivationer. Man arbejder sammen med andre mennesker, der interesserer sig for musik, kunst, film eller kultur. Det kan føre til nye venskaber og et større netværk.\n\nFrivilligt arbejde inden for kulturområdet kan også være relevant for personer, der overvejer en karriere i branchen. Studerende inden for kommunikation, eventmanagement, design eller kultur kan eksempelvis få praktisk erfaring med, hvordan arrangementer bliver planlagt og gennemført.\n\nMen man behøver ikke have en særlig kulturel baggrund for at deltage. Mange opgaver kræver først og fremmest, at man er imødekommende, ansvarlig og klar til at hjælpe. Der er plads til både mennesker, som gerne vil stå foran publikum, og dem, der helst vil arbejde bag kulisserne.\n\nEt andet aspekt er, at frivillige ofte får mulighed for at opleve lokale arrangementer på en ny måde. Man bliver en del af maskinrummet og får et indblik i alt det arbejde, der ligger bag en vellykket koncert eller festival.\n\nFlere kulturelle arrangementer er derfor afhængige af, at mennesker vælger at bruge noget af deres fritid på frivilligt arbejde. Uden disse personer ville mange events være dyrere eller vanskeligere at gennemføre.\n\nHvis du interesserer dig for kultur, kan frivilligt arbejde derfor være en oplagt måde at kombinere en hobby med et socialt engagement. Du kan møde nye mennesker, få erfaring og samtidig være med til at skabe gode oplevelser for andre.\n\nDet kræver ikke nødvendigvis et stort tidsforbrug. Mange arrangementer søger hjælp til enkelte dage eller konkrete opgaver. Det gør kulturens frivillige fællesskaber tilgængelige for mange forskellige mennesker.",
      author: "Camilla Larsen",
      imageUrl: "/assets/images/article5.jpg",
      createdAt: "2026-02-15T10:51:25.148+00:00",
    },
    {
      title: "Flere organisationer søger frivillige med digitale evner",
      content:
        "Frivilligt arbejde forbindes ofte med praktiske opgaver og direkte kontakt med mennesker. Men i takt med at flere organisationer bliver digitale, er der også kommet større efterspørgsel efter frivillige med kompetencer inden for teknologi, kommunikation og digitale medier.\n\nMange foreninger og organisationer har eksempelvis brug for hjælp til deres hjemmesider. Det kan være alt fra små opdateringer og tekstændringer til mere omfattende arbejde med struktur, design og funktionalitet. For personer med erfaring inden for webudvikling kan det være en konkret måde at bruge sine kompetencer til at hjælpe andre.\n\nSociale medier er et andet område, hvor frivillige kan gøre en forskel. Organisationer skal løbende producere opslag, billeder og videoer for at kommunikere med medlemmer og potentielle deltagere. Her kan en frivillig med interesse for sociale medier være med til at skabe større synlighed.\n\nDer kan også være brug for hjælp til grafisk design, nyhedsbreve, fotografering, video eller digitale kampagner. Det betyder, at frivilligt arbejde ikke nødvendigvis foregår fysisk i en forening. Mange digitale opgaver kan løses hjemmefra og kan derfor være fleksible.\n\nFor den frivillige kan det være en god mulighed for at arbejde med konkrete projekter. En studerende kan eksempelvis få erfaring med et rigtigt website, mens en grafiker kan opbygge en portfolio med projekter, der har haft en reel modtager.\n\nSamtidig kan organisationen få adgang til kompetencer, som den måske ikke selv har. Små foreninger har sjældent råd til at ansætte specialister inden for alle digitale områder. En frivillig kan derfor være med til at løfte organisationens digitale tilstedeværelse markant.\n\nDet betyder dog ikke, at man skal være ekspert for at hjælpe. Mange digitale opgaver kan læres undervejs, og organisationer kan ofte bruge personer, der blot har lyst til at lære mere og tage ansvar.\n\nFor personer, der arbejder professionelt med digitale områder, kan frivilligt arbejde også være en måde at dele sin viden på. Man kan eksempelvis hjælpe en forening med at forstå sociale medier, forbedre en hjemmeside eller skabe bedre digitale arbejdsgange.\n\nDen digitale udvikling betyder derfor, at mulighederne for frivilligt arbejde bliver bredere. Der er plads til både programmører, designere, fotografer, kommunikatører og personer, der bare har interesse for teknologi.\n\nHvis du har digitale kompetencer, som du gerne vil bruge på en meningsfuld måde, kan det derfor være værd at undersøge lokale organisationer og spørge, hvor de har brug for hjælp. Selv en mindre indsats kan give organisationen nye muligheder.",
      author: "Anders Madsen",
      imageUrl: "/assets/images/article6.jpg",
      createdAt: "2026-01-17T16:53:25.148+00:00",
    },
    {
      title: "Frivilligt arbejde bringer generationer sammen",
      content:
        "Frivilligt arbejde kan være med til at skabe fællesskaber på tværs af generationer. I mange foreninger og organisationer mødes unge, voksne og seniorer om en fælles opgave, og det kan give mulighed for at udveksle både erfaringer, idéer og perspektiver.\n\nI en tid, hvor mennesker ofte færdes i forskellige sociale og professionelle miljøer afhængigt af deres alder, kan frivillige fællesskaber være et sted, hvor generationerne mødes naturligt. En ung frivillig kan eksempelvis arbejde sammen med en pensionist om et arrangement, mens en erfaren foreningsperson kan hjælpe en ny frivillig med at lære opgaven.\n\nDet kan skabe relationer, som ellers ikke nødvendigvis ville opstå. De forskellige generationer kommer ofte med forskellige kompetencer. Ældre frivillige kan have mange års erfaring med organisation, planlægning og foreningsarbejde, mens yngre frivillige måske har større erfaring med digitale medier og nye kommunikationsformer.\n\nNår disse kompetencer kombineres, kan resultatet blive stærkere. En organisation kan eksempelvis bruge en erfaren frivilligs kendskab til medlemmerne sammen med en yngre frivilligs viden om sociale medier.\n\nFor de frivillige handler det dog ikke kun om kompetencer. Det sociale aspekt spiller også en stor rolle. Mange mennesker søger frivillige fællesskaber, fordi de gerne vil møde andre og have noget meningsfuldt at være en del af.\n\nDet kan være særligt værdifuldt for personer, der er flyttet til en ny by, er gået på pension eller er begyndt på en ny uddannelse. Frivilligt arbejde kan give en naturlig anledning til at møde mennesker og skabe nye relationer.\n\nSamtidig kan samarbejdet på tværs af generationer udfordre nogle af de forestillinger, man kan have om andre aldersgrupper. Når man løser en konkret opgave sammen, bliver fokus ofte flyttet fra alder til det, man faktisk kan bidrage med.\n\nForeninger og organisationer kan derfor spille en vigtig rolle i at skabe mødesteder mellem generationer. Det kræver ikke nødvendigvis særlige projekter. Ofte er det nok at give mennesker mulighed for at arbejde sammen om noget, de interesserer sig for.\n\nHvis man overvejer at blive frivillig, kan det derfor være værd at vælge et sted, hvor man får mulighed for at møde mennesker med andre erfaringer end ens egne. Det kan gøre engagementet både mere lærerigt og mere socialt.\n\nFrivilligt arbejde handler i sidste ende om at bidrage til noget fælles. Og netop det fælles mål kan være med til at bygge bro mellem generationer, der ellers måske ikke ville have haft anledning til at mødes.",
      author: "Julie Kristensen",
      imageUrl: "/assets/images/article7.jpg",
      createdAt: "2026-03-08T17:52:25.148+00:00",
    },
    {
      title: "Sportsklubber mangler frivillige hænder",
      content:
        "Sportsklubber over hele landet er afhængige af frivillige for at kunne tilbyde aktiviteter til børn, unge og voksne. Trænere og instruktører er synlige dele af klubbernes hverdag, men der ligger også mange andre opgaver bag de ugentlige træninger og kampe.\n\nDer skal arrangeres stævner, vaskes trøjer, køres spillere, sælges kaffe og planlægges aktiviteter. Der kan også være brug for hjælp til klubbens sociale medier, hjemmeside, medlemsadministration og økonomi. Mange af disse opgaver bliver løst af frivillige.\n\nUdfordringen for flere sportsklubber er, at det kan være svært at finde nok mennesker, der har tid og lyst til at tage ansvar. Mange forældre vil gerne støtte deres børn, men har samtidig en travl hverdag med arbejde og familie.\n\nDerfor forsøger flere klubber at dele opgaverne op i mindre dele. I stedet for at én person skal stå for et helt arrangement, kan flere frivillige eksempelvis tage ansvar for hver sin del. Det gør det lettere for flere at bidrage uden at skulle påtage sig en stor fast rolle.\n\nFor den enkelte frivillige kan engagementet give mange positive oplevelser. Man bliver en del af klubbens fællesskab og får mulighed for at følge børn og unge udvikle sig. For mange forældre bliver det også en måde at være tættere på deres børns fritidsliv.\n\nFrivilligt arbejde i en sportsklub kan samtidig være en god mulighed for at udvikle nye kompetencer. En person kan få erfaring med ledelse gennem trænerrollen, mens en anden kan udvikle sine organisatoriske evner ved at planlægge et stævne.\n\nDer er heller ikke nødvendigvis krav om, at man selv har dyrket sporten på højt niveau. Mange opgaver handler mere om engagement, struktur og lysten til at hjælpe. Klubberne sørger ofte for oplæring, hvis der er behov for det.\n\nDet betyder, at der kan være en plads til næsten alle. Man kan hjælpe fast hver uge, deltage ved enkelte arrangementer eller tage ansvar for en konkret opgave.\n\nHvis man gerne vil være frivillig, men er usikker på, hvad man kan bidrage med, er det ofte en god idé at kontakte en lokal klub. Man kan fortælle, hvor meget tid man har, og hvilke interesser eller kompetencer man har.\n\nNår mange mennesker giver en lille del af deres tid, kan det være nok til at holde en hel klub kørende. Derfor er frivillige ikke bare et supplement til sportsklubbernes arbejde. De er en central del af det fællesskab, som gør det muligt for tusindvis af mennesker at dyrke sport hver uge.",
      author: "Thomas Pedersen",
      imageUrl: "/assets/images/article8.jpg",
      createdAt: "2026-04-11T11:56:25.148+00:00",
    },
    {
      title: "Find det frivillige arbejde, der passer til dig",
      content:
        "Der findes mange forskellige former for frivilligt arbejde, og det kan derfor være svært at vide, hvor man skal begynde. Nogle mennesker vil gerne arbejde direkte med andre, mens andre foretrækker praktiske opgaver, natur, dyr, sport, kultur eller digitale projekter. Det vigtigste er at finde et engagement, der passer til ens interesser, tid og personlighed.\n\nEt godt sted at starte er med at overveje, hvad man selv interesserer sig for. Hvis man elsker dyr, kan man eksempelvis undersøge muligheder inden for dyrevelfærd. Er man glad for sport, kan en lokal klub være oplagt. Personer med interesse for kultur kan hjælpe på festivaler, museer eller lokale arrangementer.\n\nDet kan også være en god idé at tænke over, hvilke kompetencer man allerede har. Er man god til at tale med mennesker, kan man måske hjælpe med gæsteservice eller medlemskontakt. Er man kreativ, kan der være behov for hjælp til billeder, grafik eller sociale medier.\n\nMen frivilligt arbejde behøver ikke tage udgangspunkt i noget, man allerede kan. Det kan også være en mulighed for at lære noget nyt. En person uden erfaring med events kan eksempelvis lære at planlægge arrangementer, mens en ny frivillig i en forening kan udvikle sine samarbejdsevner.\n\nTidsforbruget er også vigtigt at overveje. Nogle opgaver kræver et fast engagement, mens andre kun tager et par timer om måneden eller foregår ved enkelte arrangementer. Det er bedre at vælge en opgave, man realistisk kan passe, end at sige ja til mere, end man har tid til.\n\nDet kan også være en fordel at starte i det små. En enkelt vagt eller et enkelt arrangement kan give et godt indtryk af, om organisationen og opgaven passer til dig. Hvis oplevelsen er positiv, kan man altid vælge at engagere sig mere senere.\n\nFor mange bliver frivilligt arbejde også en social oplevelse. Man møder mennesker, som man måske ikke ville have mødt gennem arbejde eller uddannelse. Det kan være med til at skabe nye venskaber og et større netværk.\n\nSamtidig kan det give en følelse af at bidrage til noget, der er større end en selv. Uanset om man hjælper en lokal forening, støtter en social organisation eller bidrager til et kulturelt arrangement, er ens indsats med til at skabe værdi for andre.\n\nDerfor findes der ikke én rigtig måde at være frivillig på. Det handler om at finde det sted og den opgave, hvor ens tid, interesser og kompetencer passer sammen.\n\nHvis du overvejer at blive frivillig, er det bedste råd derfor at komme i gang. Undersøg mulighederne, vælg noget, der interesserer dig, og start med et engagement, der passer til din hverdag. Det kan være begyndelsen på både nye oplevelser, nye relationer og et meningsfuldt fællesskab.",
      author: "Nanna Poulsen",
      imageUrl: "/assets/images/article9.jpg",
      createdAt: "2026-02-19T15:56:25.148+00:00",
    },
  ];

  for (const article of defaultArticles) {
    prisma.article
      .create({ data: article })
      .then(() => {
        console.log(`Article "${article.title}" created successfully.`);
      })
      .catch((error: Error) => {
        console.error(`Error creating article "${article.title}":`, error);
      });
  }
}
