import { prisma } from "../lib/prisma";

export async function jobListingSeed() {
  const defaultJobListings = [
    {
      title: "Frivillig lektiehjælper for børn og unge",
      description:
        "Hjælp børn og unge med deres skolearbejde i en hyggelig lektiecafé. Du støtter især med dansk, matematik og engelsk og hjælper den enkelte elev med at finde en god måde at arbejde på. Du behøver ikke være lærer, men du skal være tålmodig og have lyst til at skabe trygge rammer omkring læringen.",
      address: "Nørrebrogade 110",
      zipcode: 2200,
      organization: "Lektiecafé København",
      city: "København",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 1,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-03-23T17:56:25.148+00:00",
    },
    {
      title: "Frivillig underviser i dansk",
      description:
        "Hjælp voksne med at blive bedre til dansk gennem samtale, læsning og praktiske øvelser. Undervisningen foregår på små hold, hvor der er plads til forskellige niveauer. Du får materialer og en introduktion, og det vigtigste er, at du kan forklare ting på en rolig og motiverende måde.",
      address: "Vestergade 25",
      zipcode: 8000,
      organization: "Sprogvenner Aarhus",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 1,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-08-14T15:53:35.555+00:00",
    },
    {
      title: "Frivillig matematikmentor",
      description:
        "Vi søger en frivillig, der vil hjælpe unge med matematik og give dem større tro på egne evner. Du mødes med en elev eller en lille gruppe én gang om ugen og arbejder med opgaver fra skolen. Du behøver ikke have en læreruddannelse, men du skal være fagligt sikker og god til at forklare ting på flere måder.",
      address: "Skolegade 18",
      zipcode: 9000,
      organization: "Aalborg Læringsværksted",
      city: "Aalborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 1,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-04T13:13:54.825+00:00",
    },
    {
      title: "Frivillig lektiehjælper i engelsk",
      description:
        "Hjælp skoleelever med engelsk grammatik, læsning og mundtlig træning. Opgaven tilpasses den enkelte elevs niveau, så fokus kan være både på lektier og på at få større selvtillid i faget. Vi sørger for adgang til relevante materialer og en kort introduktion.",
      address: "Kirkegade 14",
      zipcode: 6700,
      organization: "Esbjerg Ungecenter",
      city: "Esbjerg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 1,
      regionId: 3,
      workTypeId: 1,
      createdAt: "2026-03-12T22:18:43.053+00:00",
    },
    {
      title: "Frivillig mentor for unge",
      description:
        "Som frivillig mentor bliver du en fast voksenkontakt for en ung, der har brug for støtte til skole, uddannelse og hverdagsstruktur. I aftaler sammen konkrete mål og taler løbende om, hvordan det går. Det vigtigste er stabilitet, nærvær og lysten til at lytte.",
      address: "Jernbanegade 8",
      zipcode: 5000,
      organization: "Odense Ungenetværk",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 1,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-07-25T23:36:02.920+00:00",
    },
    {
      title: "Frivillig lektiehjælper online",
      description:
        "Vi søger frivillige, der vil hjælpe børn og unge med lektier via videoopkald. Du kan især hjælpe med dansk, matematik eller engelsk og aftaler selv faste tidspunkter med eleven. Det er en fleksibel opgave, som passer godt til dig, der gerne vil undervise hjemmefra.",
      address: "Vesterbrogade 42",
      zipcode: 1620,
      organization: "Digital Lektiehjælp",
      city: "København",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 1,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-03-10T19:17:16.062+00:00",
    },
    {
      title: "Frivillig læsetræner for børn",
      description:
        "Hjælp børn med at få større glæde ved at læse. Du læser sammen med barnet, taler om historierne og laver små øvelser, der styrker ordforråd og læseforståelse. Opgaven kræver ikke en læreruddannelse, men du skal have tålmodighed og kunne skabe en positiv oplevelse omkring læsning.",
      address: "Parkvej 12",
      zipcode: 4700,
      organization: "Læs Sammen Næstved",
      city: "Næstved",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 1,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-07-26T03:07:06.023+00:00",
    },
    {
      title: "Frivillig naturformidler for skoleklasser",
      description:
        "Hjælp skoleklasser med at opleve og forstå naturen gennem praktiske aktiviteter. Du kan blandt andet være med til at undersøge planter, insekter og biodiversitet og fortælle om livet i de lokale naturområder. Vi giver dig materialer og introduktion til vores undervisningsforløb.",
      address: "Skovvej 14",
      zipcode: 9000,
      organization: "Nordjysk Naturcenter",
      city: "Aalborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 1,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-08-09T23:22:19.094+00:00",
    },
    {
      title: "Frivillig sprogmakker for unge",
      description:
        "Bliv sprogmakker for en ung, der gerne vil øve dansk i uformelle situationer. I kan tale om hverdagen, skole, fritid og interesser eller lave små læse- og skriveøvelser sammen. Du behøver ikke være underviser; det vigtigste er, at du er god til at samtale og møder den unge med respekt.",
      address: "Banegårdspladsen 6",
      zipcode: 8000,
      organization: "Sprogmakker Aarhus",
      city: "Aarhus",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 1,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-06-14T08:11:10.402+00:00",
    },
    {
      title: "Frivillig lektiecafé-koordinator",
      description:
        "Hjælp med at skabe struktur omkring vores ugentlige lektiecafé. Du tager imod de frivillige, hjælper med at fordele eleverne og sørger for, at alle ved, hvad der skal ske. Derudover kan du selv hjælpe med lektier, når der er behov for det. Erfaring med børn og unge er en fordel.",
      address: "Østergade 21",
      zipcode: 4800,
      organization: "Nykøbing Lektiecafé",
      city: "Nykøbing Falster",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 1,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-05-27T12:05:50.565+00:00",
    },
    {
      title: "Frivillig underviser i computerfærdigheder",
      description:
        "Hjælp voksne og ældre med at blive mere trygge ved computere og digitale løsninger. Du kan blandt andet undervise i e-mail, tekstbehandling, digitale selvbetjeningsløsninger og sikker brug af internettet. Undervisningen foregår i et roligt tempo, hvor spørgsmål er en naturlig del af læringen.",
      address: "Havnegade 31",
      zipcode: 5800,
      organization: "Nyborg Digitale Fællesskab",
      city: "Nyborg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 1,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-09-07T10:31:05.219+00:00",
    },
    {
      title: "Frivillig studiestøtte for unge",
      description:
        "Vi søger frivillige, der kan hjælpe unge med at få struktur på deres skolearbejde. Du kan støtte med planlægning, opgaveskrivning, læsning og forberedelse til prøver. Du behøver ikke kunne alle fag, da opgaven først og fremmest handler om motivation og gode studievaner.",
      address: "Vesterbro 77",
      zipcode: 9000,
      organization: "Ungdommens Studieværksted",
      city: "Aalborg",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 1,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-11T14:13:48.378+00:00",
    },
    {
      title: "Frivillig webudvikler",
      description:
        "Vi søger en frivillig webudvikler, som vil hjælpe vores forening med at vedligeholde og forbedre hjemmesiden. Du kommer blandt andet til at arbejde med mindre ændringer, fejlrettelser og nye funktioner. Du behøver ikke kunne alle teknologier på forhånd, og opgaverne kan tilpasses dine kompetencer.",
      address: "Kronprinsessegade 8",
      zipcode: 1306,
      organization: "FrivilligTech Danmark",
      city: "København",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 2,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-05-23T01:20:21.020+00:00",
    },
    {
      title: "IT-supporter for frivilligorganisation",
      description:
        "Hjælp medarbejdere og frivillige med almindelige IT-problemer i hverdagen. Det kan være opsætning af computere, hjælp til software, printere eller netværk. Du behøver ikke have en formel IT-uddannelse, men du skal være tålmodig og kunne forklare tekniske problemer på en enkel måde.",
      address: "Havnepladsen 6",
      zipcode: 5000,
      organization: "Fyns Frivilligcenter",
      city: "Odense",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 2,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-08-15T02:07:12.858+00:00",
    },
    {
      title: "Frivillig dataansvarlig",
      description:
        "Hjælp vores forening med at skabe bedre struktur i medlemsdata, arrangementer og simple rapporter. Opgaverne kan bestå af oprydning i data, kontrol af oplysninger og arbejde i Excel eller Google Sheets. Erfaring med digitale systemer er en fordel, men du får en introduktion til vores arbejdsgange.",
      address: "Søndergade 42",
      zipcode: 8000,
      organization: "Aarhus Frivillignetværk",
      city: "Aarhus",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 2,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-04-19T02:39:56.288+00:00",
    },
    {
      title: "Frivillig WordPress-hjælper",
      description:
        "Vi søger en frivillig, der kan hjælpe med at opdatere vores WordPress-hjemmeside. Du kommer til at lægge nyheder op, rette tekster, indsætte billeder og foretage mindre ændringer. Det er en fleksibel opgave, hvor du kan arbejde hjemmefra og selv være med til at planlægge tiden.",
      address: "Studiestræde 24",
      zipcode: 1554,
      organization: "Foreningsnet Danmark",
      city: "København",
      workHome: "Remote",
      userId: 2,
      jobCategoryId: 2,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-06-19T17:32:35.293+00:00",
    },
    {
      title: "Frivillig UX-hjælper",
      description:
        "Hjælp os med at gøre vores digitale løsninger nemmere at bruge. Du kan blandt andet gennemgå sider, finde områder der er svære at forstå og komme med forslag til forbedringer. Vi søger ikke nødvendigvis en professionel designer, men en person med interesse for brugeroplevelser og digitale produkter.",
      address: "Møllegade 9",
      zipcode: 8000,
      organization: "Digitalt Fællesskab Aarhus",
      city: "Aarhus",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 2,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-08-26T00:46:46.714+00:00",
    },
    {
      title: "Frivillig cybersikkerhedsvejleder",
      description:
        "Hjælp en mindre forening med at få styr på grundlæggende digital sikkerhed. Du kan blandt andet gennemgå adgangskoder, totrinslogin, backup og sikker håndtering af dokumenter. Opgaven er rådgivende, og du behøver ikke arbejde med avanceret sikkerhed; vi har brug for hjælp til de praktiske grundprincipper.",
      address: "Nørregade 19",
      zipcode: 9000,
      organization: "Sikker Forening Aalborg",
      city: "Aalborg",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 2,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-07-05T11:03:15.179+00:00",
    },
    {
      title: "Frivillig teknisk projektassistent",
      description:
        "Vi søger en teknisk interesseret frivillig, der kan hjælpe med at holde overblik over mindre digitale projekter. Du kan blandt andet følge op på opgaver, teste nye funktioner og dokumentere ændringer. Det er en god mulighed for dig, der gerne vil bruge eller udvikle dine projekt- og IT-kompetencer.",
      address: "Vesterbrogade 42",
      zipcode: 1620,
      organization: "Frivillige Digitale Projekter",
      city: "København",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 2,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-05-22T22:53:33.920+00:00",
    },
    {
      title: "Frivillig hjælp til digitale kurser",
      description:
        "Hjælp vores undervisere med at gennemføre kurser i digitale værktøjer for ældre og andre borgere. Du assisterer kursister, når de går i stå, og viser dem trin for trin, hvordan de løser almindelige digitale opgaver. Det kræver ikke en IT-uddannelse, men du skal være god til at forklare ting tålmodigt.",
      address: "Vestergade 33",
      zipcode: 5000,
      organization: "Odense Digitalhjælp",
      city: "Odense",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 2,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-04-28T17:00:23.213+00:00",
    },
    {
      title: "Frivillig app-tester",
      description:
        "Vi søger frivillige med teknisk interesse til at teste en ny app, som skal gøre det lettere at finde lokale fællesskaber. Du skal afprøve forskellige funktioner, beskrive fejl og give feedback på, hvad der er nemt eller svært at forstå. Du behøver ikke være udvikler, da brugerens perspektiv er det vigtigste.",
      address: "Algade 15",
      zipcode: 4000,
      organization: "Roskilde Fællesskaber",
      city: "Roskilde",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 2,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-09-05T21:33:24.958+00:00",
    },
    {
      title: "Frivillig frontendudvikler",
      description:
        "Hjælp vores lille organisation med at videreudvikle en offentlig informationsside. Vi arbejder primært med HTML, CSS og JavaScript, og du får mulighed for at arbejde med konkrete funktioner sammen med andre frivillige. Du skal kunne arbejde selvstændigt og have lyst til at skrive vedligeholdbar kode.",
      address: "Vesterbro Torv 4",
      zipcode: 8000,
      organization: "Åben Web Aarhus",
      city: "Aarhus",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 2,
      regionId: 2,
      workTypeId: 2,
      createdAt: "2026-09-03T12:47:30.706+00:00",
    },
    {
      title: "Frivillig teknisk dokumentationsskribent",
      description:
        "Vi mangler hjælp til at skrive og strukturere dokumentation til vores digitale løsninger. Du skal gøre tekniske instruktioner lettere at forstå for nye frivillige og brugere. Erfaring med teknisk dokumentation er en fordel, men det vigtigste er, at du kan forklare digitale arbejdsgange klart og præcist.",
      address: "Østerbro 22",
      zipcode: 9000,
      organization: "Teknik for Alle",
      city: "Aalborg",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 2,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-06-17T20:49:45.738+00:00",
    },
    {
      title: "Frivillig IT-mentor for seniorer",
      description:
        "Hjælp seniorer med at blive mere fortrolige med digitale værktøjer og tjenester. Du kan blandt andet hjælpe med smartphone, tablet, e-mail, videomøder og sikker brug af internettet. Undervisningen foregår én til én eller i små grupper, og du behøver ikke være IT-ekspert – tålmodighed og evnen til at forklare ting enkelt er det vigtigste.",
      address: "Seniorvej 8",
      zipcode: 5800,
      organization: "Nyborg Digitalhjælp",
      city: "Nyborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 2,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-08-07T01:24:08.352+00:00",
    },
    {
      title: "Frivillig systemadministrator",
      description:
        "Hjælp vores lille organisation med at holde styr på brugere, adgang og de digitale systemer, som de frivillige anvender. Opgaverne er primært vedligeholdelse, oprettelse af brugere og almindelig fejlfinding. Erfaring med IT-drift er en fordel, og du får stor frihed til at tilrettelægge opgaverne efter dine muligheder.",
      address: "Teknologivej 11",
      zipcode: 9000,
      organization: "Aalborg Digitale Frivillige",
      city: "Aalborg",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 2,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-28T08:49:50.567+00:00",
    },
    {
      title: "Frivillig til digitalisering af forening",
      description:
        "Hjælp en lokal forening med at få mere af deres administrative arbejde over på digitale løsninger. Du kan blandt andet hjælpe med formularer, delte dokumenter, digitale arbejdsgange og strukturering af filer. Opgaven passer godt til dig, der kan lide at gøre systemer enklere og mere overskuelige for andre.",
      address: "Foreningsvej 27",
      zipcode: 4000,
      organization: "Roskilde Digital Forening",
      city: "Roskilde",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 2,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-04-14T08:52:53.340+00:00",
    },
    {
      title: "Frivillig kulturvært på museum",
      description:
        "Bliv frivillig kulturvært og giv museumsgæster en god oplevelse. Du tager imod besøgende, svarer på spørgsmål og fortæller om aktuelle udstillinger og arrangementer. Du behøver ikke være kunsthistoriker, men du skal være interesseret i kultur og have lyst til at tale med mennesker.",
      address: "Jernbanegade 13",
      zipcode: 5000,
      organization: "Odense Kulturmuseum",
      city: "Odense",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 3,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-03-22T16:40:11.864+00:00",
    },
    {
      title: "Frivillig til lokale koncerter",
      description:
        "Hjælp med at afvikle koncerter og kulturelle arrangementer. Opgaverne kan være modtagelse af gæster, garderobe, opsætning og praktisk hjælp omkring kunstnere og teknikere. Du behøver ingen erfaring fra koncertbranchen, men skal være mødestabil og have lyst til at være en del af et aktivt kulturmiljø.",
      address: "Kulturkajen 4",
      zipcode: 9000,
      organization: "Aalborg Kulturforening",
      city: "Aalborg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 3,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-05-12T04:15:46.925+00:00",
    },
    {
      title: "Frivillig kreativ værkstedsassistent",
      description:
        "Hjælp børn, unge og voksne i vores åbne kreative værksted, hvor vi arbejder med maling, keramik, tekstil og andre materialer. Du hjælper med materialer og praktiske spørgsmål og bidrager til en hyggelig atmosfære. Du behøver ikke være professionel kunstner.",
      address: "Skolegade 17",
      zipcode: 6700,
      organization: "Kreative Hænder Esbjerg",
      city: "Esbjerg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 3,
      regionId: 3,
      workTypeId: 1,
      createdAt: "2026-07-13T06:33:13.359+00:00",
    },
    {
      title: "Frivillig teatermedhjælper",
      description:
        "Vær med bag kulisserne på vores lokale teater. Du kan hjælpe med sceneskift, rekvisitter, publikumsmodtagelse og praktiske opgaver før og efter forestillinger. Vi sørger for oplæring, og du behøver ikke have erfaring fra teaterverdenen. Det vigtigste er, at du har lyst til at være en del af et hold.",
      address: "Teaterstræde 6",
      zipcode: 8000,
      organization: "Aarhus Lokalteater",
      city: "Aarhus",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 3,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-06-16T18:36:27.479+00:00",
    },
    {
      title: "Frivillig museumsformidler",
      description:
        "Hjælp med at formidle lokale historier til børn og familier på museet. Du deltager i rundvisninger, aktiviteter og mindre workshops, hvor gæsterne bliver inviteret til at undersøge historien gennem genstande og fortællinger. Du får introduktion til vores udstillinger og formidlingsmaterialer.",
      address: "Museumsgade 4",
      zipcode: 4000,
      organization: "Roskilde Historiske Museum",
      city: "Roskilde",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 3,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-08-22T20:17:19.584+00:00",
    },
    {
      title: "Frivillig musikarrangør",
      description:
        "Hjælp vores forening med at planlægge små koncerter og musikarrangementer. Du kan arbejde med kontakt til musikere, praktisk planlægning, tidsplaner og koordinering på selve dagen. Erfaring med arrangementer er en fordel, men vi søger især en person med engagement og sans for struktur.",
      address: "Havnegade 12",
      zipcode: 5000,
      organization: "Musikbyen Odense",
      city: "Odense",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 3,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-03-12T03:32:54.420+00:00",
    },
    {
      title: "Frivillig lokalhistoriker",
      description:
        "Vi søger frivillige med interesse for lokalhistorie til at hjælpe med at indsamle og formidle fortællinger fra lokalområdet. Du kan arbejde med gamle fotografier, interviews, arkivmateriale og korte tekster til vores hjemmeside. Du behøver ikke være historiker, men nysgerrighed og sans for detaljer er vigtigt.",
      address: "Torvegade 8",
      zipcode: 3700,
      organization: "Bornholms Historieforening",
      city: "Rønne",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 3,
      regionId: 6,
      workTypeId: 3,
      createdAt: "2026-08-17T04:35:43.172+00:00",
    },
    {
      title: "Frivillig biblioteksassistent",
      description:
        "Hjælp biblioteket med kulturelle aktiviteter, bogarrangementer og praktiske opgaver omkring vores fællesskaber. Du kan blandt andet hjælpe gæster, gøre lokaler klar og være med til at afvikle læseklubber og foredrag. Interesse for litteratur og kultur er en fordel.",
      address: "Bibliotekstorvet 1",
      zipcode: 8000,
      organization: "Aarhus Kulturhus",
      city: "Aarhus",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 3,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-04-06T10:45:38.896+00:00",
    },
    {
      title: "Frivillig festivalmedhjælper",
      description:
        "Bliv en del af holdet bag vores lokale kulturfestival. Der er brug for hjælp til opsætning, gæstemodtagelse, aktiviteter og oprydning. Vagterne er fleksible, og du kan vælge enkelte dage eller flere vagter. Det er en social mulighed for at opleve festivalen fra første række.",
      address: "Festivalpladsen 2",
      zipcode: 5000,
      organization: "Fyns Kulturfestival",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 3,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-09-01T04:45:48.060+00:00",
    },
    {
      title: "Frivillig kunstudstillingsassistent",
      description:
        "Hjælp med at gøre vores kunstudstillinger klar og byde gæster velkommen. Opgaverne består blandt andet af praktisk opsætning, information til besøgende og lettere koordinering med kunstnere. Du behøver ikke have kunstfaglig uddannelse, men interesse for kunst er en fordel.",
      address: "Kunstvej 7",
      zipcode: 7400,
      organization: "Herning Kunstforening",
      city: "Herning",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 3,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-03-29T07:15:34.898+00:00",
    },
    {
      title: "Frivillig håndværker til renovering af fælleshus",
      description:
        "Hjælp med maling, mindre reparationer, opsætning af hylder og vedligeholdelse af vores fælleshus. Du behøver ikke kunne det hele, da vi matcher opgaverne med dine kompetencer. Vi sørger for materialer og værktøj, og du bliver en del af et lille team, der arbejder sammen om bedre lokale rammer.",
      address: "Møllevej 22",
      zipcode: 7400,
      organization: "Herning Fælleshus",
      city: "Herning",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 4,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-03-17T17:12:20.129+00:00",
    },
    {
      title: "Frivillig cykelmekaniker",
      description:
        "Hjælp lokale borgere med at få deres cykler til at fungere igen. Du kan arbejde med punkteringer, bremser, gear og almindelig vedligeholdelse. Du behøver ikke være uddannet cykelmekaniker, men du skal have praktisk sans og lyst til at arbejde med hænderne sammen med andre frivillige.",
      address: "Østerbro 31",
      zipcode: 9000,
      organization: "Aalborg Cykelværksted",
      city: "Aalborg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 4,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-05T06:41:36.362+00:00",
    },
    {
      title: "Frivillig til have- og anlægsarbejde",
      description:
        "Hjælp med beskæring, lugning, plantning og vedligeholdelse af fælles grønne områder. Du behøver ikke være gartner, men erfaring med havearbejde er en fordel. Opgaverne varierer efter årstiden, og du kan deltage fast eller på enkelte aktivitetsdage.",
      address: "Parkvej 9",
      zipcode: 4700,
      organization: "Næstved Grønne Fællesskab",
      city: "Næstved",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 4,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-06-20T02:55:55.998+00:00",
    },
    {
      title: "Frivillig maler til aktivitetscenter",
      description:
        "Vi søger frivillige, der kan hjælpe med at friske vores aktivitetscenter op. Opgaverne består primært af maling af vægge, døre og mindre træværk. Du behøver ikke være professionel maler, men du skal have erfaring med almindeligt malerarbejde og kunne arbejde omhyggeligt.",
      address: "Skovgade 14",
      zipcode: 8000,
      organization: "Aarhus Aktivitetshus",
      city: "Aarhus",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 4,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-04-02T11:02:44.677+00:00",
    },
    {
      title: "Frivillig møbelreparatør",
      description:
        "Hjælp med at reparere og istandsætte brugte møbler, som ellers ville ende som affald. Du kan blandt andet slibe, male, samle og udføre mindre reparationer. Vi har både værktøj og materialer, og du får mulighed for at arbejde sammen med andre med interesse for håndværk og genbrug.",
      address: "Industrivej 6",
      zipcode: 5000,
      organization: "Odense Genbrugsværksted",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 4,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-08-19T10:45:08.506+00:00",
    },
    {
      title: "Frivillig træværkstedsassistent",
      description:
        "Bliv en del af vores træværksted, hvor frivillige fremstiller og reparerer simple møbler og inventar. Du hjælper med at måle, save, slibe og samle efter dine evner. Sikkerhed er vigtig, og du får introduktion til værktøj og arbejdsrutiner, inden du starter.",
      address: "Værkstedsvej 11",
      zipcode: 9000,
      organization: "Nordjysk Byggeværksted",
      city: "Aalborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 4,
      regionId: 1,
      workTypeId: 1,
      createdAt: "2026-07-12T21:04:07.934+00:00",
    },
    {
      title: "Frivillig reparatør på genbrugsstation",
      description:
        "Hjælp med at undersøge og reparere mindre genstande, der bliver afleveret til genbrug. Det kan være lamper, møbler, køkkenudstyr eller andre ting, hvor en lille indsats kan forlænge levetiden. Du skal have praktisk sans og være interesseret i reparation og genbrug.",
      address: "Genbrugsvej 4",
      zipcode: 6700,
      organization: "Esbjerg Reparationsværksted",
      city: "Esbjerg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 4,
      regionId: 3,
      workTypeId: 3,
      createdAt: "2026-06-19T14:22:57.946+00:00",
    },
    {
      title: "Frivillig vedligeholdelsesassistent",
      description:
        "Hjælp vores forening med små praktiske vedligeholdelsesopgaver på vores faciliteter. Det kan være at hænge ting op, samle møbler, reparere mindre skader og holde udendørsarealer pæne. Du behøver ikke være faglært, men skal være praktisk anlagt og ansvarsbevidst.",
      address: "Foreningsvej 19",
      zipcode: 5800,
      organization: "Nyborg Fællesforening",
      city: "Nyborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 4,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-03-30T06:11:21.416+00:00",
    },
    {
      title: "Frivillig syværkstedsassistent",
      description:
        "Hjælp med at reparere tøj og tekstiler i vores åbne syværksted. Du kan blandt andet sy knapper i, reparere sømme og hjælpe besøgende med små projekter. Erfaring med symaskine er en fordel, men du kan også lære opgaven sammen med vores øvrige frivillige.",
      address: "Algade 27",
      zipcode: 4000,
      organization: "Roskilde Syfællesskab",
      city: "Roskilde",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 4,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-05-13T03:51:29.825+00:00",
    },
    {
      title: "Frivillig cykelbygger",
      description:
        "Vi istandsætter brugte cykler, som gives videre til mennesker, der har brug for en pålidelig cykel. Du hjælper med rengøring, justering, udskiftning af dele og almindelig service. Du behøver ikke være ekspert, da vi arbejder sammen og hjælper hinanden med de tekniske opgaver.",
      address: "Cykelgade 5",
      zipcode: 8000,
      organization: "Cykler til Alle Aarhus",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 4,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-09-07T16:16:44.738+00:00",
    },
    {
      title: "Frivillig håndværksmentor",
      description:
        "Hjælp unge med at prøve kræfter med praktiske håndværksopgaver i vores værksted. Du kan lære fra dig inden for træ, maling, reparation eller andre områder, du selv mestrer. Fokus er på fællesskab, praktiske færdigheder og at give de unge succesoplevelser.",
      address: "Fabriksvej 15",
      zipcode: 9000,
      organization: "Aalborg Ungeværksted",
      city: "Aalborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 4,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-05-18T15:35:53.946+00:00",
    },
    {
      title: "Frivillig boligistandsætter",
      description:
        "Vi hjælper mennesker, der flytter fra midlertidige boliger til deres eget hjem, med små praktiske opgaver. Du kan blandt andet hjælpe med at samle møbler, male, hænge lamper op og løse mindre vedligeholdelsesopgaver. Du skal have praktisk erfaring og kunne arbejde respektfuldt i andre menneskers hjem.",
      address: "Vestergade 52",
      zipcode: 5000,
      organization: "Nyt Hjem Odense",
      city: "Odense",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 4,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-05-18T15:51:16.248+00:00",
    },
    {
      title: "Frivillig værktøjsansvarlig",
      description:
        "Hjælp med at holde styr på værktøj og udstyr i vores fælles værksted. Du sørger for, at værktøj er på plads, fungerer og er klar til brug, og hjælper nye frivillige med de grundlæggende sikkerhedsregler. Praktisk erfaring fra et værksted er en fordel.",
      address: "Værkstedsvej 8",
      zipcode: 1620,
      organization: "Værkstedet København",
      city: "København",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 4,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-06-06T14:48:19.144+00:00",
    },
    {
      title: "Frivillig lagerassistent",
      description:
        "Hjælp med at modtage, sortere og klargøre donationer på vores lager. Opgaverne består blandt andet af varemodtagelse, mærkning, organisering og pakning af varer til udlevering. Du behøver ingen særlige kvalifikationer, men skal kunne arbejde struktureret og have det godt med fysisk arbejde.",
      address: "Industrivej 18",
      zipcode: 7100,
      organization: "Vejle Hjælpecentral",
      city: "Vejle",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 5,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-05-03T19:30:22.429+00:00",
    },
    {
      title: "Frivillig produktionshjælper på genbrugscenter",
      description:
        "Hjælp med at sortere, reparere og klargøre donerede genstande til genbrug. Du kan blandt andet arbejde med sortering, rengøring, lettere reparationer og klargøring af varer. Vi sørger for oplæring og finder opgaver, der passer til dine praktiske evner.",
      address: "Industriparken 7",
      zipcode: 8600,
      organization: "Silkeborg Genbrug",
      city: "Silkeborg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 5,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-06-22T07:26:14.603+00:00",
    },
    {
      title: "Frivillig værkstedsmedhjælper",
      description:
        "Hjælp til på vores sociale værksted med reparation, genbrug og forskellige mindre produktionsopgaver. Du kan sortere materialer, bruge almindeligt håndværktøj og gøre produkter klar til salg. Du får en introduktion og mulighed for at lære nye praktiske færdigheder undervejs.",
      address: "Fabriksvej 15",
      zipcode: 3700,
      organization: "Bornholms Værksted",
      city: "Rønne",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 5,
      regionId: 6,
      workTypeId: 1,
      createdAt: "2026-08-19T23:59:47.477+00:00",
    },
    {
      title: "Frivillig sorteringsmedarbejder",
      description:
        "Vi søger frivillige til sortering af doneret tøj, bøger og brugsting. Du vurderer genstandenes stand, sorterer dem efter kategori og gør dem klar til genbrug eller salg. Arbejdet er praktisk og foregår sammen med andre frivillige i et aktivt miljø.",
      address: "Genbrugsvej 12",
      zipcode: 9000,
      organization: "Nordjysk Genbrug",
      city: "Aalborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 5,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-23T12:12:19.681+00:00",
    },
    {
      title: "Frivillig pakkeassistent",
      description:
        "Hjælp med at pakke nødhjælp og andre donationer, som skal ud til lokale familier og sociale tilbud. Du arbejder efter enkle pakkelister og hjælper med at holde orden på lageret. Det er vigtigt, at du er grundig og kan samarbejde med andre.",
      address: "Lagervej 4",
      zipcode: 5000,
      organization: "Odense Hjælpelager",
      city: "Odense",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 5,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-05-11T02:15:26.083+00:00",
    },
    {
      title: "Frivillig reparationsmedarbejder",
      description:
        "Hjælp med at gøre donerede produkter klar til et nyt liv. Opgaverne kan være rengøring, afprøvning, mindre reparationer og sortering. Du behøver ikke være faglært, men en praktisk tilgang og interesse for genbrug er en stor fordel.",
      address: "Industrivej 29",
      zipcode: 4000,
      organization: "Roskilde Genbrugsværksted",
      city: "Roskilde",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 5,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-07-02T13:36:46.182+00:00",
    },
    {
      title: "Frivillig logistikassistent",
      description:
        "Hjælp vores organisation med at koordinere vareflow mellem lager, butikker og lokale aktiviteter. Du kommer blandt andet til at registrere varer, planlægge mindre leverancer og holde overblik over beholdningen. Struktur og ansvarlighed er vigtigere end formel erfaring.",
      address: "Havnevej 18",
      zipcode: 6700,
      organization: "Esbjerg Social Logistik",
      city: "Esbjerg",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 5,
      regionId: 3,
      workTypeId: 3,
      createdAt: "2026-04-24T21:06:31.691+00:00",
    },
    {
      title: "Frivillig lagerkoordinator",
      description:
        "Vi søger en frivillig, der kan hjælpe med at skabe struktur på vores lager. Du hjælper med vareplacering, optælling og koordinering af de andre lagerfrivillige. Opgaven passer godt til dig, der kan lide orden, systematik og praktiske arbejdsdage.",
      address: "Industrivej 3",
      zipcode: 7400,
      organization: "Herning Fælleslager",
      city: "Herning",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 5,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-06-27T22:20:46.067+00:00",
    },
    {
      title: "Frivillig miljøsorterer",
      description:
        "Hjælp med at sortere materialer, så mest muligt kan genbruges. Du arbejder blandt andet med papir, metal, plast og forskellige brugsting og sørger for, at materialerne ender det rigtige sted. Du får instruktion i vores sorteringsregler og sikkerhed.",
      address: "Genbrugsvej 20",
      zipcode: 5800,
      organization: "Nyborg Miljøværksted",
      city: "Nyborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 5,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-08-06T12:45:21.832+00:00",
    },
    {
      title: "Frivillig klargøringsmedarbejder",
      description:
        "Hjælp med at klargøre møbler og andre donerede varer til vores genbrugsbutik. Du kan vaske, rengøre, mærke og organisere varerne og hjælpe med at flytte dem på plads. Det er et aktivt frivilligjob, hvor man hurtigt kan se resultatet af sin indsats.",
      address: "Butiksvej 9",
      zipcode: 8000,
      organization: "Aarhus Genbrug",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 5,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-05-24T11:15:08.531+00:00",
    },
    {
      title: "Frivillig distributionshjælper",
      description:
        "Hjælp med at gøre donationer klar til distribution til lokale sociale tilbud. Du arbejder med pakning, mærkning og koordinering af mindre leverancer. Opgaven kræver overblik og pålidelighed, men du får en grundig introduktion til vores rutiner.",
      address: "Logistikvej 7",
      zipcode: 1620,
      organization: "Københavns Donorcenter",
      city: "København",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 5,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-06-21T04:16:33.072+00:00",
    },
    {
      title: "Frivillig cafémedarbejder",
      description:
        "Hjælp i vores sociale café, hvor mennesker fra lokalområdet mødes over kaffe, mad og samtaler. Du tager imod gæster, laver kaffe, serverer lette måltider og hjælper med at holde caféen hyggelig. Du behøver ikke erfaring fra café eller restaurant, da vi sørger for introduktion.",
      address: "Vesterbrogade 88",
      zipcode: 1620,
      organization: "Café Fællesskab",
      city: "København",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 6,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-05-28T22:58:45.034+00:00",
    },
    {
      title: "Frivillig besøgsven",
      description:
        "Bliv besøgsven for en ældre borger, der savner mere social kontakt i hverdagen. I kan drikke kaffe, gå en tur, spille et spil eller bare tale sammen. Det handler ikke om praktisk hjemmehjælp, men om nærvær og fællesskab. Vi matcher dig med en borger ud fra interesser og geografi.",
      address: "Søndergade 12",
      zipcode: 8000,
      organization: "Aarhus Besøgsvenner",
      city: "Aarhus",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 6,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-06-19T03:11:32.345+00:00",
    },
    {
      title: "Frivillig hjælper ved lokale arrangementer",
      description:
        "Hjælp med praktiske opgaver ved fællesspisninger, aktiviteter og lokale arrangementer. Du kan tage imod gæster, hjælpe med opsætning, servering og oprydning. Opgaverne varierer fra gang til gang, så det passer godt til dig, der gerne vil prøve forskellige typer frivilligt arbejde.",
      address: "Torvegade 5",
      zipcode: 5800,
      organization: "Nyborg Lokalfællesskab",
      city: "Nyborg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 6,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-07-24T12:50:39.854+00:00",
    },
    {
      title: "Frivillig madudleverer",
      description:
        "Hjælp med at uddele overskudsmad til mennesker i lokalområdet. Du hjælper med at modtage maden, sortere den og gøre portioner klar til udlevering. Det er vigtigt, at du kan samarbejde og følge vores enkle retningslinjer for hygiejne og fødevaresikkerhed.",
      address: "Madvej 6",
      zipcode: 9000,
      organization: "Aalborg Madfællesskab",
      city: "Aalborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 6,
      regionId: 1,
      workTypeId: 1,
      createdAt: "2026-08-11T23:05:06.313+00:00",
    },
    {
      title: "Frivillig vært i fælleshus",
      description:
        "Vær med til at skabe en varm og inkluderende stemning i vores fælleshus. Du tager imod besøgende, svarer på spørgsmål og hjælper folk med at finde de aktiviteter, der passer til dem. Det vigtigste er, at du er imødekommende og har lyst til at møde mange forskellige mennesker.",
      address: "Fællesskabsvej 4",
      zipcode: 4700,
      organization: "Næstved Fælleshus",
      city: "Næstved",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 6,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-08-02T21:45:21.223+00:00",
    },
    {
      title: "Frivillig telefonven",
      description:
        "Bliv telefonven for en person, der savner mere kontakt i hverdagen. I aftaler et fast tidspunkt, hvor I taler sammen over telefonen. Samtalerne kan handle om alt fra hverdagsoplevelser og interesser til aktuelle begivenheder. Du får vejledning og støtte fra vores koordinator.",
      address: "Telefonvej 10",
      zipcode: 5000,
      organization: "Fyns Telefonvenner",
      city: "Odense",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 6,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-08-25T00:14:52.228+00:00",
    },
    {
      title: "Frivillig aktivitetsmedhjælper",
      description:
        "Hjælp med at gennemføre sociale aktiviteter for børn, unge og voksne. Du kan blandt andet hjælpe med spil, kreative aktiviteter, fællesspisning og udflugter. Du behøver ingen særlige kvalifikationer, men du skal være engageret og have lyst til at skabe gode oplevelser.",
      address: "Aktivitetsvej 7",
      zipcode: 7400,
      organization: "Herning Fællesskab",
      city: "Herning",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 6,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-08-27T04:11:49.802+00:00",
    },
    {
      title: "Frivillig køkkenhjælper",
      description:
        "Hjælp i vores fælleskøkken, hvor vi laver varme måltider til mennesker, der har brug for et måltid og et sted at være. Du hjælper med forberedelse, madlavning, anretning og oprydning. Du behøver ikke være kok, men skal have lyst til at samarbejde og følge køkkenets hygiejneregler.",
      address: "Vestergade 61",
      zipcode: 6700,
      organization: "Esbjerg Fælleskøkken",
      city: "Esbjerg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 6,
      regionId: 3,
      workTypeId: 1,
      createdAt: "2026-07-23T11:36:59.672+00:00",
    },
    {
      title: "Frivillig ledsager",
      description:
        "Vi søger frivillige, der vil ledsage mennesker til aktiviteter, aftaler eller sociale arrangementer, som de ellers har svært ved at komme til alene. Du skal være stabil, omsorgsfuld og god til at kommunikere. Opgaverne aftales individuelt og tilpasses den enkelte persons behov.",
      address: "Sundhedsvej 3",
      zipcode: 8000,
      organization: "Aarhus Ledsagernetværk",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 6,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-05-30T10:01:55.408+00:00",
    },
    {
      title: "Frivillig aktivitetsvært for ældre",
      description:
        "Hjælp med at skabe hyggelige aktiviteter for ældre borgere. Det kan være kortspil, højtlæsning, gåture, musik eller fællessang. Du behøver ikke have erfaring med ældrearbejde, men du skal have lyst til at være nærværende og bidrage til et trygt fællesskab.",
      address: "Parkgade 22",
      zipcode: 4000,
      organization: "Roskilde Seniorfællesskab",
      city: "Roskilde",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 6,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-07-14T06:00:51.501+00:00",
    },
    {
      title: "Frivillig genbrugsbutiksmedarbejder",
      description:
        "Hjælp i vores genbrugsbutik med at tage imod donationer, sortere varer, fylde hylder op og hjælpe kunder. Du får mulighed for at arbejde med mange forskellige opgaver og bliver en del af et socialt team. Erfaring fra butik er ikke nødvendig.",
      address: "Algade 31",
      zipcode: 9000,
      organization: "Aalborg Genbrug",
      city: "Aalborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 6,
      regionId: 1,
      workTypeId: 1,
      createdAt: "2026-06-23T14:32:39.493+00:00",
    },
    {
      title: "Frivillig velkomstvært",
      description:
        "Vær den første person, som gæster møder, når de kommer til vores sociale tilbud. Du tager imod besøgende, hjælper dem med praktiske spørgsmål og viser dem rundt. En venlig og imødekommende tilgang er vigtigere end erfaring, og du får en introduktion til stedet.",
      address: "Kulturvej 8",
      zipcode: 5000,
      organization: "Odense Mødested",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 6,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-03-20T13:34:26.892+00:00",
    },
    {
      title: "Frivillig madchauffør",
      description:
        "Hjælp med at køre overskudsmad fra butikker og restauranter til lokale sociale tilbud. Du skal have almindeligt kørekort og kunne håndtere kasser med madvarer. Ruterne planlægges på forhånd, og du får en introduktion til både transport og fødevaresikkerhed.",
      address: "Logistikgade 12",
      zipcode: 1620,
      organization: "MadRed København",
      city: "København",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 6,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-06-17T21:54:42.216+00:00",
    },
    {
      title: "Frivillig aktivitetsleder",
      description:
        "Vi søger en frivillig, der kan planlægge og gennemføre mindre sociale aktiviteter. Det kan være brætspilsaftener, gåture, kreative workshops eller fællesspisninger. Du får frihed til at komme med egne idéer, men vi hjælper med lokaler, materialer og praktisk planlægning.",
      address: "Fælleshusvej 16",
      zipcode: 3700,
      organization: "Rønne Fællesskab",
      city: "Rønne",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 6,
      regionId: 6,
      workTypeId: 3,
      createdAt: "2026-05-05T21:37:56.879+00:00",
    },
    {
      title: "Frivillig cafévært",
      description:
        "Hjælp med at skabe en hyggelig stemning i vores café for unge. Du tager imod gæster, hjælper med simple caféopgaver og er med til at skabe et trygt sted at mødes. Du behøver ikke være meget ældre end målgruppen, men du skal være ansvarlig og god til at skabe kontakt.",
      address: "Ungdomsgade 4",
      zipcode: 8000,
      organization: "UngAarhus Café",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 6,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-07-16T22:15:36.036+00:00",
    },
    {
      title: "Frivillig praktisk hjælper til sociale tilbud",
      description:
        "Hjælp med en bred vifte af praktiske opgaver i vores sociale tilbud. Det kan være opsætning af lokaler, flytning af mindre ting, oprydning og klargøring til aktiviteter. Du vælger selv, hvor meget du vil deltage, og vi sørger for tydelige opgaver.",
      address: "Foreningsgade 19",
      zipcode: 5800,
      organization: "Nyborg Socialcenter",
      city: "Nyborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 6,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-04-24T18:23:58.681+00:00",
    },
    {
      title: "Frivillig kommunikationsmedarbejder",
      description:
        "Hjælp os med vores kommunikation ved at skrive korte nyheder til hjemmesiden, udarbejde opslag til sociale medier og fortælle om vores aktiviteter. Du skal kunne formulere dig godt på dansk og have sans for målgrupper og formidling. Opgaverne kan udføres hjemmefra.",
      address: "Studiestræde 24",
      zipcode: 1554,
      organization: "Frivillige Stemmer",
      city: "København",
      workHome: "Remote",
      userId: 2,
      jobCategoryId: 7,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-03-31T15:00:16.270+00:00",
    },
    {
      title: "Frivillig fotograf til sociale aktiviteter",
      description:
        "Tag billeder fra vores arrangementer, aktiviteter og frivillige fællesskaber, som vi kan bruge på hjemmeside, nyhedsbrev og sociale medier. Du behøver ikke være professionel fotograf, men du skal kunne arbejde respektfuldt med mennesker og have blik for gode motiver.",
      address: "Havnegade 41",
      zipcode: 5000,
      organization: "Fyns Frivillige",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 7,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-04-18T09:52:35.100+00:00",
    },
    {
      title: "Frivillig SoMe-redaktør",
      description:
        "Hjælp med at planlægge og skrive opslag til vores sociale medier. Du kommer til at finde historier, lave indholdskalender og være med til at skabe en mere aktiv digital tilstedeværelse. Vi søger en kreativ person, der har lyst til at komme med egne idéer.",
      address: "Banegårdspladsen 3",
      zipcode: 9000,
      organization: "Nordjysk Fællesskab",
      city: "Aalborg",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 7,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-06-16T00:39:48.646+00:00",
    },
    {
      title: "Frivillig tekstforfatter",
      description:
        "Vi søger en frivillig, der kan hjælpe med at skrive tekster til vores hjemmeside, nyhedsbreve og informationsmateriale. Du skal kunne skrive klart og levende på dansk og være god til at tilpasse sproget til forskellige målgrupper. Du arbejder tæt sammen med vores øvrige kommunikationsfrivillige.",
      address: "Nørregade 15",
      zipcode: 8000,
      organization: "Aarhus Foreningsliv",
      city: "Aarhus",
      workHome: "Remote",
      userId: 2,
      jobCategoryId: 7,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-04-06T01:15:39.712+00:00",
    },
    {
      title: "Frivillig nyhedsbrevredaktør",
      description:
        "Hjælp med at samle historier fra vores frivillige og organisationer og omsætte dem til et månedligt nyhedsbrev. Du skal finde de vigtigste historier, skrive korte tekster og hjælpe med opsætningen. Erfaring med nyhedsbreve er en fordel, men ikke et krav.",
      address: "Vesterbrogade 55",
      zipcode: 1620,
      organization: "Frivillig Nyt København",
      city: "København",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 7,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-04-10T01:36:15.091+00:00",
    },
    {
      title: "Frivillig pressemedarbejder",
      description:
        "Hjælp vores organisation med at fortælle lokale medier om vores aktiviteter og resultater. Opgaverne kan være at skrive pressemeddelelser, finde gode historier og kontakte journalister. Erfaring med pressearbejde er en fordel, men vi hjælper dig godt i gang.",
      address: "Torvegade 17",
      zipcode: 6700,
      organization: "Esbjerg Frivilligforum",
      city: "Esbjerg",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 7,
      regionId: 3,
      workTypeId: 3,
      createdAt: "2026-04-19T10:12:33.230+00:00",
    },
    {
      title: "Frivillig videoproducer",
      description:
        "Lav korte videoer, der fortæller om vores frivillige og de mennesker, vi hjælper. Du kan filme interviews, aktiviteter og små historier og hjælpe med enkel redigering. Du behøver ikke professionelt udstyr, hvis du kan skabe godt indhold med de værktøjer, du har.",
      address: "Kulturvej 14",
      zipcode: 5000,
      organization: "Fyns Frivilligmedie",
      city: "Odense",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 7,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-09-02T19:31:11.286+00:00",
    },
    {
      title: "Frivillig kommunikationskoordinator",
      description:
        "Hjælp med at koordinere vores kommunikationsopgaver og sikre, at historier og informationer bliver delt til tiden. Du får kontakt med flere teams og hjælper med at planlægge indhold til hjemmeside, sociale medier og nyhedsbrev. Struktur og gode skriveevner er vigtigt.",
      address: "Nytorv 8",
      zipcode: 9000,
      organization: "Aalborg Foreningsnetværk",
      city: "Aalborg",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 7,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-08-28T22:00:27.280+00:00",
    },
    {
      title: "Frivillig grafisk kommunikationshjælper",
      description:
        "Hjælp med at lave simple grafikker til opslag, plakater og digitale kampagner. Du kan arbejde i Canva, Figma eller et andet relevant værktøj. Vi søger en person med sans for layout og lyst til at omsætte vores budskaber til indhold, der er let at forstå.",
      address: "Designgade 6",
      zipcode: 8000,
      organization: "Aarhus Frivilligdesign",
      city: "Aarhus",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 7,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-08-12T17:44:40.101+00:00",
    },
    {
      title: "Frivillig interviewskribent",
      description:
        "Interview frivillige og samarbejdspartnere og skriv deres historier til vores hjemmeside. Du skal kunne stille gode spørgsmål og omsætte samtaler til levende og respektfulde tekster. Opgaverne kan udføres fleksibelt og passer godt til dig, der interesserer dig for mennesker og fortællinger.",
      address: "Jernbanegade 28",
      zipcode: 5000,
      organization: "Odense Frivilligfortællinger",
      city: "Odense",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 7,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-05-24T05:15:15.065+00:00",
    },
    {
      title: "Frivillig kampagnemedarbejder",
      description:
        "Hjælp med at udvikle og gennemføre en kampagne, der skal få flere mennesker til at engagere sig frivilligt. Du kan bidrage med idéer, tekst, sociale medier og koordinering. Det er en god mulighed for dig, der gerne vil prøve kræfter med kommunikation i praksis.",
      address: "Kampagnevej 2",
      zipcode: 4700,
      organization: "Frivillig Næstved",
      city: "Næstved",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 7,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-05-12T11:52:44.740+00:00",
    },
    {
      title: "Frivillig kommunikationsfotograf",
      description:
        "Tag stemningsbilleder fra vores aktiviteter og hjælp med at finde motiver, der fortæller, hvad vores organisation laver. Du arbejder tæt sammen med kommunikationsteamet og får mulighed for at udvikle en lille billedbank, som kan bruges på tværs af vores kanaler.",
      address: "Havnevej 12",
      zipcode: 3700,
      organization: "Bornholm Fællesskab",
      city: "Rønne",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 7,
      regionId: 6,
      workTypeId: 3,
      createdAt: "2026-08-02T10:44:58.163+00:00",
    },
    {
      title: "Frivillig administrativ assistent",
      description:
        "Hjælp vores forening med almindelige administrative opgaver som dokumenthåndtering, registrering, kalenderstyring og praktisk koordinering. Du får en introduktion til vores systemer og arbejder sammen med andre frivillige. Struktur, grundighed og lyst til at hjælpe er vigtigere end en bestemt uddannelse.",
      address: "Vesterbrogade 73",
      zipcode: 1620,
      organization: "Københavns Frivilligcenter",
      city: "København",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 8,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-06-24T07:22:03.548+00:00",
    },
    {
      title: "Frivillig kontormedhjælper",
      description:
        "Vi søger en frivillig til vores kontor, som kan hjælpe med lettere administrative og praktiske opgaver. Det kan være kopiering, sortering af dokumenter, registrering af oplysninger og klargøring til møder. Du arbejder i et roligt miljø sammen med medarbejdere og andre frivillige.",
      address: "Vestergade 44",
      zipcode: 8000,
      organization: "Aarhus Sociale Kontor",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 8,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-08-14T14:40:54.411+00:00",
    },
    {
      title: "Frivillig kalenderkoordinator",
      description:
        "Hjælp med at holde styr på møder, frivilligvagter og arrangementer i vores kalender. Du får ansvar for at opdatere aftaler, følge op på ændringer og sikre, at de relevante personer har den rigtige information. Opgaven kræver overblik og sans for detaljer.",
      address: "Nørregade 21",
      zipcode: 9000,
      organization: "Aalborg Frivilligservice",
      city: "Aalborg",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 8,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-06-13T22:22:32.268+00:00",
    },
    {
      title: "Frivillig medlemsadministrator",
      description:
        "Hjælp med at holde medlemsoplysninger opdaterede og besvare simple henvendelser fra medlemmer. Du kommer til at arbejde i vores medlemsdatabase og hjælpe med udsendelser og praktiske administrative opgaver. Du får grundig oplæring i systemet og vores procedurer.",
      address: "Jernbanegade 19",
      zipcode: 5000,
      organization: "Odense Foreningsservice",
      city: "Odense",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 8,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-07-07T21:19:10.652+00:00",
    },
    {
      title: "Frivillig mødekoordinator",
      description:
        "Hjælp med at planlægge og koordinere møder for vores frivillige og samarbejdspartnere. Du sørger for invitationer, lokaler, dagsordener og praktisk information. Du behøver ikke erfaring som koordinator, men du skal være organiseret og god til at følge op.",
      address: "Torvegade 12",
      zipcode: 6700,
      organization: "Esbjerg Frivillignetværk",
      city: "Esbjerg",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 8,
      regionId: 3,
      workTypeId: 3,
      createdAt: "2026-08-07T01:19:14.941+00:00",
    },
    {
      title: "Frivillig økonomimedhjælper",
      description:
        "Hjælp vores lille forening med simple økonomiopgaver som bilag, kvitteringer og registrering af udgifter. Du behøver ikke være revisor, men erfaring med regneark og tal er en fordel. Vi sørger for tydelige arbejdsgange og adgang til de systemer, du skal bruge.",
      address: "Banegårdspladsen 7",
      zipcode: 8000,
      organization: "Aarhus Foreningsøkonomi",
      city: "Aarhus",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 8,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-07-22T16:40:56.164+00:00",
    },
    {
      title: "Frivillig receptionist",
      description:
        "Tag imod besøgende på vores frivilligcenter og hjælp dem med at finde den rette person eller aktivitet. Du besvarer også telefoniske henvendelser og hjælper med enkle praktiske opgaver. Du skal være imødekommende, stabil og god til at bevare overblikket.",
      address: "Stationsvej 3",
      zipcode: 5000,
      organization: "Fyns Frivilligcenter",
      city: "Odense",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 8,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-08-31T12:03:50.636+00:00",
    },
    {
      title: "Frivillig dokumentationsassistent",
      description:
        "Hjælp med at organisere dokumenter, referater og andre materialer, så de er nemme at finde for vores frivillige. Du skal arbejde systematisk og have blik for detaljer. Det er en fleksibel opgave, hvor en stor del af arbejdet kan udføres hjemmefra.",
      address: "Kontorvej 8",
      zipcode: 4000,
      organization: "Roskilde Foreningsarkiv",
      city: "Roskilde",
      workHome: "Remote",
      userId: 1,
      jobCategoryId: 8,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-03-19T20:52:21.388+00:00",
    },
    {
      title: "Frivillig bookingkoordinator",
      description:
        "Hjælp med at administrere bookinger af lokaler til møder, aktiviteter og arrangementer. Du holder kalenderen opdateret, svarer på forespørgsler og sikrer, at praktiske informationer bliver sendt videre. Erfaring med administration er en fordel, men vi lærer dig vores system.",
      address: "Kulturvej 22",
      zipcode: 7400,
      organization: "Herning Fælleshus",
      city: "Herning",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 8,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-06-12T06:42:31.138+00:00",
    },
    {
      title: "Frivillig dataregistrator",
      description:
        "Hjælp med at registrere oplysninger fra medlemslister, tilmeldinger og spørgeskemaer. Du skal være grundig og kunne arbejde koncentreret med gentagne opgaver. Det er en fleksibel rolle, som kan udføres både på kontoret og hjemmefra.",
      address: "Søndergade 30",
      zipcode: 4700,
      organization: "Næstved Frivilligservice",
      city: "Næstved",
      workHome: "Remote",
      userId: 2,
      jobCategoryId: 8,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-08-10T20:09:12.319+00:00",
    },
    {
      title: "Frivillig sekretær for forening",
      description:
        "Hjælp bestyrelsen med praktiske sekretæropgaver som mødeindkaldelser, referater, dokumenter og opfølgning på aftaler. Du behøver ikke have været sekretær før, men du skal kunne formulere dig klart og holde styr på flere små opgaver ad gangen.",
      address: "Foreningsgade 11",
      zipcode: 3700,
      organization: "Bornholms Foreningsråd",
      city: "Rønne",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 8,
      regionId: 6,
      workTypeId: 1,
      createdAt: "2026-06-24T07:00:24.604+00:00",
    },
    {
      title: "Frivillig HR-assistent",
      description:
        "Hjælp med praktiske opgaver omkring vores frivillige, blandt andet onboarding, registrering af kontaktoplysninger og koordinering af introduktioner. Du kommer til at have kontakt med mange mennesker, så det er vigtigt, at du er venlig, struktureret og god til at følge op.",
      address: "Vesterbrogade 36",
      zipcode: 1620,
      organization: "FrivilligNet København",
      city: "København",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 8,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-07-11T22:05:07.057+00:00",
    },
    {
      title: "Frivillig kontorvært",
      description:
        "Hjælp med at skabe et velfungerende kontor for vores frivillige. Du tager imod gæster, sørger for mødelokaler og hjælper med praktiske spørgsmål. Opgaven passer godt til dig, der kan lide at have kontakt med mennesker og samtidig løse små administrative opgaver.",
      address: "Møllepladsen 5",
      zipcode: 8000,
      organization: "Aarhus FrivilligHub",
      city: "Aarhus",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 8,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-08-05T09:18:44.161+00:00",
    },
    {
      title: "Frivillig projektadministrativ hjælper",
      description:
        "Hjælp projektgruppen med at holde styr på deadlines, dokumenter, møder og opfølgning. Du får et godt indblik i, hvordan frivillige projekter bliver planlagt og gennemført. Erfaring med administration eller projektarbejde er en fordel, men ikke et krav.",
      address: "Projektvej 9",
      zipcode: 9000,
      organization: "Nordjysk Projektfællesskab",
      city: "Aalborg",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 8,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-15T10:49:00.966+00:00",
    },
    {
      title: "Frivillig medlemsservice",
      description:
        "Hjælp medlemmer med praktiske spørgsmål via e-mail og telefon og sørg for, at henvendelser bliver sendt videre til de rigtige personer. Du får faste retningslinjer og svarskabeloner, men der er også plads til at bruge din egen dømmekraft og venlige kommunikation.",
      address: "Vestergade 17",
      zipcode: 5000,
      organization: "Odense Foreningsliv",
      city: "Odense",
      workHome: "Remote",
      userId: 3,
      jobCategoryId: 8,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-05-26T22:25:03.019+00:00",
    },
    {
      title: "Frivillig regnskabsassistent",
      description:
        "Vi søger en frivillig, der kan hjælpe med at holde orden i bilag og simple regnskabsopgaver. Du kommer til at arbejde tæt sammen med vores kasserer og får adgang til de nødvendige systemer. Erfaring med regnskab eller bogføring er en fordel, men opgaverne kan tilpasses dit niveau.",
      address: "Regnskabsvej 4",
      zipcode: 6700,
      organization: "Esbjerg Foreningsøkonomi",
      city: "Esbjerg",
      workHome: "Hybrid",
      userId: 1,
      jobCategoryId: 8,
      regionId: 3,
      workTypeId: 1,
      createdAt: "2026-07-14T14:22:08.915+00:00",
    },
    {
      title: "Frivillig mødesekretær",
      description:
        "Hjælp med at forberede møder, tage noter og samle beslutninger i korte referater. Du skal kunne lytte, skrive klart og holde styr på information. Opgaven kan kombineres med andre kontoropgaver og tilrettelægges fleksibelt.",
      address: "Rådhusvej 13",
      zipcode: 5800,
      organization: "Nyborg Frivilligråd",
      city: "Nyborg",
      workHome: "Hybrid",
      userId: 3,
      jobCategoryId: 8,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-03-17T04:18:57.853+00:00",
    },
    {
      title: "Frivillig kontorassistent på deltid",
      description:
        "Hjælp et lokalt frivilligcenter med en række administrative opgaver et par timer om ugen. Det kan være sortering af post, registrering, klargøring af materialer og hjælp til arrangementer. Du får en varieret hverdag og bliver en del af et lille team.",
      address: "Centergade 6",
      zipcode: 7400,
      organization: "Herning Frivilligcenter",
      city: "Herning",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 8,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-06-11T04:34:51.721+00:00",
    },
    {
      title: "Frivillig til dyreinternat",
      description:
        "Hjælp med at passe dyr på vores internat. Opgaverne kan være fodring, rengøring, aktivering og praktiske opgaver omkring dyrene. Du behøver ikke have en særlig uddannelse, men du skal være ansvarsbevidst, rolig og have respekt for dyr med forskellige behov.",
      address: "Dyrevej 6",
      zipcode: 4000,
      organization: "Roskilde Dyrehjælp",
      city: "Roskilde",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 9,
      regionId: 5,
      workTypeId: 1,
      createdAt: "2026-09-02T06:09:54.267+00:00",
    },
    {
      title: "Frivillig natur- og strandplejer",
      description:
        "Hjælp med at passe lokale naturområder og strande. Vi samler affald, vedligeholder stier og hjælper med mindre plejeopgaver. Aktiviteterne foregår udendørs og er både praktiske og sociale. Du behøver ingen særlige kvalifikationer.",
      address: "Strandvejen 27",
      zipcode: 3700,
      organization: "Bornholms Naturvenner",
      city: "Rønne",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 9,
      regionId: 6,
      workTypeId: 3,
      createdAt: "2026-08-23T08:59:31.536+00:00",
    },
    {
      title: "Frivillig motionsmakker",
      description:
        "Bliv motionsmakker for en person, der gerne vil være mere aktiv. I kan gå ture, cykle eller lave simple øvelser sammen. Fokus er ikke på præstation, men på motivation og fællesskab. Vi matcher jer ud fra interesser og muligheder.",
      address: "Idrætsvej 9",
      zipcode: 8000,
      organization: "Aarhus Motion Sammen",
      city: "Aarhus",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 9,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-04-14T18:48:56.014+00:00",
    },
    {
      title: "Frivillig lektiebuddy for familier",
      description:
        "Hjælp familier med at få en mere rolig hverdag omkring skole og lektier. Du kan støtte med planlægning, læsning eller praktiske skoleopgaver. Rollen er fleksibel og tilpasses familiens behov, og du får støtte fra vores frivilligkoordinator.",
      address: "Familievej 12",
      zipcode: 9000,
      organization: "Aalborg Familiehjælp",
      city: "Aalborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 9,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-05-19T14:26:17.999+00:00",
    },
    {
      title: "Frivillig indsamler til velgørenhed",
      description:
        "Hjælp med at samle ind til vores sociale arbejde ved lokale arrangementer og indsamlingsdage. Du møder borgere på gader og pladser, fortæller kort om formålet og tager imod bidrag. Du får en introduktion og arbejder sammen med andre frivillige.",
      address: "Torvet 4",
      zipcode: 5000,
      organization: "Fyns Velgørenhed",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 9,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-03-23T05:56:25.373+00:00",
    },
    {
      title: "Frivillig eventhjælper",
      description:
        "Hjælp med at gennemføre events for vores lokale fællesskab. Opgaverne kan være opsætning, registrering af deltagere, praktisk hjælp under arrangementet og oprydning. Det er en fleksibel rolle, hvor du kan vælge enkelte arrangementer frem for en fast ugentlig vagt.",
      address: "Eventvej 7",
      zipcode: 1620,
      organization: "Københavns Fællesskab",
      city: "København",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 9,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-05-18T11:29:52.729+00:00",
    },
    {
      title: "Frivillig legetøjsværtsassistent",
      description:
        "Hjælp børn og familier i vores åbne legetøjsværksted, hvor brugt legetøj får nyt liv. Du hjælper med sortering, rengøring og små reparationer og kan være med til at skabe kreative aktiviteter. Det vigtigste er, at du har lyst til at arbejde praktisk og sammen med andre.",
      address: "Legetøjsvej 3",
      zipcode: 6700,
      organization: "Esbjerg Legetøjsværksted",
      city: "Esbjerg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 9,
      regionId: 3,
      workTypeId: 1,
      createdAt: "2026-06-18T06:54:01.083+00:00",
    },
    {
      title: "Frivillig turleder",
      description:
        "Planlæg og gennemfør korte fælles gåture for lokale borgere. Du vælger ruten, byder deltagerne velkommen og sørger for, at tempoet passer til gruppen. Det er en social rolle, hvor det vigtigste er at skabe et inkluderende fællesskab omkring motion og frisk luft.",
      address: "Parkvej 18",
      zipcode: 5800,
      organization: "Nyborg Gåfællesskab",
      city: "Nyborg",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 9,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-04-25T16:44:51.926+00:00",
    },
    {
      title: "Frivillig fællesskabsvært",
      description:
        "Hjælp med at skabe et trygt mødested for mennesker, der gerne vil lære andre at kende. Du tager imod nye deltagere, hjælper med aktiviteter og sørger for, at ingen står alene. Rollen kræver ikke en bestemt faglig baggrund, men empati og lyst til fællesskab er vigtigt.",
      address: "Fællesskabsvej 11",
      zipcode: 7400,
      organization: "Herning Mødested",
      city: "Herning",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 9,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-04-22T12:37:11.056+00:00",
    },
    {
      title: "Frivillig støtteperson ved fritidsaktiviteter",
      description:
        "Hjælp børn og unge med at deltage i lokale fritidsaktiviteter. Du kan følge dem til træning, hjælpe med praktiske ting og være en ekstra tryg voksen omkring aktiviteten. Opgaven aftales individuelt og kræver stabilitet og gode samarbejdsevner.",
      address: "Sportsvej 6",
      zipcode: 9000,
      organization: "Aalborg Fritid for Alle",
      city: "Aalborg",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 9,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-04-15T20:38:15.306+00:00",
    },
    {
      title: "Frivillig naturguide",
      description:
        "Del din interesse for naturen med andre ved at arrangere små ture i lokalområdet. Du kan fortælle om planter, dyr og landskab eller blot skabe en hyggelig gåtur med plads til spørgsmål og samtaler. Du behøver ikke være naturfaglig ekspert.",
      address: "Skovvej 25",
      zipcode: 8000,
      organization: "Aarhus Naturfællesskab",
      city: "Aarhus",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 9,
      regionId: 2,
      workTypeId: 3,
      createdAt: "2026-07-17T17:37:35.530+00:00",
    },
    {
      title: "Frivillig hjælper på social campingtur",
      description:
        "Hjælp med praktiske opgaver på vores årlige campingtur for familier og børn. Du kan hjælpe med madlavning, aktiviteter, opsætning og daglig koordinering. Det er en intensiv, men social frivilligopgave, hvor du bliver en vigtig del af fællesskabet.",
      address: "Campingvej 2",
      zipcode: 4700,
      organization: "Næstved Familiecamp",
      city: "Næstved",
      workHome: "On-site",
      userId: 1,
      jobCategoryId: 9,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-03-12T23:35:52.423+00:00",
    },
    {
      title: "Frivillig bogindsamler",
      description:
        "Hjælp med at modtage, sortere og pakke brugte bøger, som skal gives videre til skoler, biblioteker og sociale tilbud. Du arbejder sammen med andre frivillige og får mulighed for at gøre en konkret forskel gennem genbrug og læseglæde.",
      address: "Bogvej 9",
      zipcode: 5000,
      organization: "Odense Bøger Videre",
      city: "Odense",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 9,
      regionId: 4,
      workTypeId: 1,
      createdAt: "2026-03-22T10:26:51.691+00:00",
    },
    {
      title: "Frivillig besøgsven for unge",
      description:
        "Bliv en fast voksenkontakt for en ung, som gerne vil have mere socialt fællesskab i hverdagen. I kan gå en tur, spille spil, tale om interesser eller lave en aktivitet sammen. Rollen handler om stabilitet og nærvær og kræver ikke en bestemt uddannelse.",
      address: "Ungdomsvej 15",
      zipcode: 9000,
      organization: "Aalborg Ungenetværk",
      city: "Aalborg",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 9,
      regionId: 1,
      workTypeId: 3,
      createdAt: "2026-07-11T03:04:00.562+00:00",
    },
    {
      title: "Frivillig miljøambassadør",
      description:
        "Hjælp med at skabe mere opmærksomhed om genbrug, affaldssortering og bæredygtige hverdagsvaner. Du kan deltage i lokale events, lave små informationsaktiviteter og tale med borgere om miljø. Du får materiale og introduktion til vores vigtigste budskaber.",
      address: "Miljøvej 4",
      zipcode: 1620,
      organization: "Grøn København",
      city: "København",
      workHome: "Hybrid",
      userId: 2,
      jobCategoryId: 9,
      regionId: 5,
      workTypeId: 3,
      createdAt: "2026-06-13T15:08:09.315+00:00",
    },
    {
      title: "Frivillig fællesspisningsvært",
      description:
        "Hjælp med at arrangere og afvikle fællesspisninger for lokale borgere. Du kan hjælpe med borddækning, modtagelse af gæster, servering og oprydning. Det vigtigste er at bidrage til en afslappet og inkluderende stemning, hvor mennesker føler sig velkomne.",
      address: "Spisevej 8",
      zipcode: 8000,
      organization: "Aarhus Fællesspisning",
      city: "Aarhus",
      workHome: "On-site",
      userId: 3,
      jobCategoryId: 9,
      regionId: 2,
      workTypeId: 1,
      createdAt: "2026-05-23T23:11:55.667+00:00",
    },
    {
      title: "Frivillig udflugtsassistent",
      description:
        "Hjælp med at planlægge og gennemføre små udflugter for lokale borgere. Du kan hjælpe med transport, deltagerliste, praktiske spørgsmål og aktiviteter undervejs. Du behøver ikke være rejseleder, men skal være god til at bevare overblikket og hjælpe andre.",
      address: "Udflugtsvej 5",
      zipcode: 5000,
      organization: "Odense Oplevelser",
      city: "Odense",
      workHome: "On-site",
      userId: 2,
      jobCategoryId: 9,
      regionId: 4,
      workTypeId: 3,
      createdAt: "2026-03-23T00:29:47.025+00:00",
    },
  ];

  // 123 jobs
  // Fordeling: category 1 = 12, category 2 = 14, category 3 = 10, category 4 = 13, category 5 = 11, category 6 = 16, category 7 = 12, category 8 = 18, category 9 = 17

  for (const listing of defaultJobListings) {
    await prisma.jobListing.upsert({
      where: { id: defaultJobListings.indexOf(listing) + 1 },
      update: {},
      create: listing,
    });
    console.log("JobListing", listing.title, " created succesfully");
  }
}
